### ISSUE TITLE
repository template v1 for all RoboSter repositories

### ISSUE THREAD

**Issue by katunilya** [RoboSter/repo-template#1]
### Problem

In order not to repeat same actions every time we create repositories
As a RoboSter team member
I want to have repository template that will utilize all the open source standard requirements for any new repository

### Solution

Repository should provide

* simple `README.md` template
* `.gitignore`
* Contribution Guidelines
* Apache 2.0 License
* Issues & Pull Request templates

**Comment by bymse** [comment]
why Apache 2.0 License?

**Comment by katunilya** [comment]
@bymse 
@OlegMoiseev said so

**Comment by bymse** [comment]
Let's discuss mr/pr and issues settings?
What can you suggest? 

As for me:
I prefer to use use merge commit everytime, because it's easier to understand what's happened when you look at branches.

**Comment by katunilya** [comment]
@bymse 

quickly made a pull request for discussion #2

I prefer the same practice

**Comment by bymse** [comment]
### issues
I suggest those types: 
- feature, as general issue for large improvement of functionality
- task, simple issue for 1-3 commits, for example: new api method for some currently available info
- infra, for infrastructure improvements

**Comment by bymse** [comment]
What's about `actions` ?

**Comment by katunilya** [comment]
GitHub Actions? Just didn’t get the question

**Comment by bymse** [comment]
Yep, GitHub Actions, for pr as example: WIP check, that block merging

**Comment by katunilya** [comment]
Got it! Anything else?

**Comment by bymse** [comment]
That's all for now, I guess
